### ISSUE TITLE
Compatibility: If curl is not available, use wget?

### ISSUE THREAD

**Issue by 0x27** [zMarch/Orc#19]
I noticed some hardcoded curl calls in various functions, we should have a fallback to " wget -q -O-" for the event curl is unavailable on the system. 

We could also check for the LWP POST/GET commands, lwp-request/etc. After all, never know what kind of weird shit we end up on.

**Comment by zMarch** [comment]
I've been thinking about this - it's the same problem as ifconfig vs ip, etc. I think a soon-to-come update is going to determine whether awk/curl is available, and if they AREN'T, we could try and fall back on LWP.
but please god not LWP

**Comment by UlrichBerntien** [comment]
In pull request #32 a new function orc_loadURL is added.

The function should load a https and http URL via curl, wget, perl or python.

I have not add a lwp-request call because I have not found an option to switch of the SSL certification check. lwp-request is a perl script. Hence the perl script inside the orc_loadURL function could be a sufficient replacement.
