### ISSUE TITLE
Removing getnet

### ISSUE THREAD

**Issue by zMarch** [zMarch/Orc#51]
Debating it because honestly, it doesn't work, it's terrible, and it's causing half our issues in shellcheck. We could always write something better/not terrible. At the very least, should probably get rid of the ipcalc bits, I think.

**Comment by UlrichBerntien** [comment]
I prefer a new implementation of getnet. The code is very complex I fear to destruct the function if I try to fix only the shellcheck warnings.

I consider to implement parts in awk (mawk and POSIX awk compatible) because in awk is a powerfull language. A pure shell script could also an option. If a good shell code becomes to hard a perl script and a python script could be a fallback; better to support systems with perl or python than supporting no system. Today I have not a conclusion.

Likely an implementation with several helper functions, e.g. a ipconfig/ip link  wrapper, will be a good solution. Also ipcalc/other solution is a candidate for a wrapper function.

In the mean time we could create a branch, named getnet_rework or simlar, with the getnet function and with "getnet() { echo 'comming soon  back' }" in the master branch.

**Comment by zMarch** [comment]
I think a new branch for a rework is an excellent idea; just created one. I'll remove getnet from master when I get the chance. Having collaboration on getnet this time will hopefully mean the code won't be so complex and bad!

**Comment by zMarch** [comment]
Getnet clutter removed! now to develop something better
